version: '3.7'

services:
  db:
    image: "postgres"
    environment:
      # - POSTGRES_HOST_AUTH_METHOD = trust
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    ports:
    - 5432:5432
    # command: bash -c ""

  backend:
    build: .
    ports: 
      - 3000:3000
    depends_on:
      - db

volumes:
  postgres_data: